"""Flat CIS policy definitions.

Add new controls to the list matching the Windows tool that owns the setting.
The executor functions do not need to change when more policies are added.
"""

NET_ACCOUNTS = [
    {
        "cis_id": "1.1.1",
        "name": "Enforce password history",
        "label": "Length of password history maintained",
        "command": "uniquepw",
        "required": 24,
        "default": 0,
        "operator": "gte",
        "input_min": 1,
        "input_max": 24,
        "unit": " password(s)",
    },
    {
        "cis_id": "1.1.2",
        "name": "Maximum password age",
        "label": "Maximum password age (days)",
        "command": "maxpwage",
        "required": 365,
        "default": 42,
        "operator": "between",
        "minimum": 1,
        "maximum": 365,
        "input_min": 1,
        "input_max": 999,
        "unit": " day(s)",
    },
    {
        "cis_id": "1.1.3",
        "name": "Minimum password age",
        "label": "Minimum password age (days)",
        "command": "minpwage",
        "required": 1,
        "default": 0,
        "operator": "gte",
        "input_min": 1,
        "input_max": 998,
        "unit": " day(s)",
    },
    {
        "cis_id": "1.1.4",
        "name": "Minimum password length",
        "label": "Minimum password length",
        "command": "minpwlen",
        "required": 14,
        "default": 0,
        "operator": "gte",
        "input_min": 1,
        "input_max": 128,
        "unit": " character(s)",
    },
    {
        "cis_id": "1.2.1",
        "name": "Account lockout duration",
        "label": "Lockout duration (minutes)",
        "command": "lockoutduration",
        "required": 15,
        "default": 30,
        "operator": "gte",
        "input_min": 1,
        "input_max": 99999,
        "unit": " minute(s)",
    },
    {
        "cis_id": "1.2.2",
        "name": "Account lockout threshold",
        "label": "Lockout threshold",
        "command": "lockoutthreshold",
        "required": 5,
        "default": 0,
        "operator": "between",
        "minimum": 1,
        "maximum": 5,
        "input_min": 1,
        "input_max": 999,
        "unit": " invalid attempt(s)",
    },
    {
        "cis_id": "1.2.4",
        "name": "Reset account lockout counter after",
        "label": "Lockout observation window (minutes)",
        "command": "lockoutwindow",
        "required": 15,
        "default": 30,
        "operator": "gte",
        "input_min": 1,
        "input_max": 99999,
        "unit": " minute(s)",
    },
]

SECEDIT_POLICIES = [
    {
        "cis_id": "1.1.5",
        "name": "Password must meet complexity requirements",
        "key": "PasswordComplexity",
        "required": 1,
        "default": 0,
        "display": {0: "Disabled", 1: "Enabled"},
        "input_min": 0,
        "input_max": 1,
    },
    {
        "cis_id": "1.1.7",
        "name": "Store passwords using reversible encryption",
        "key": "ClearTextPassword",
        "required": 0,
        "default": 0,
        "display": {0: "Disabled", 1: "Enabled"},
        "input_min": 0,
        "input_max": 1,
    },
    {
        "cis_id": "1.2.3",
        "name": "Allow Administrator account lockout",
        "key": "AllowAdministratorLockout",
        "required": 1,
        "default": 0,
        "missing_value": 0,
        "display": {0: "Disabled", 1: "Enabled"},
        "input_min": 0,
        "input_max": 1,
    },
    {
        "cis_id": "2.2.5",
        "name": "Allow log on locally",
        "key": "SeInteractiveLogonRight",
        "required": "*S-1-5-32-544,*S-1-5-32-545",
        "default": "*S-1-5-32-544,*S-1-5-32-545,*S-1-5-32-551",
        "is_string": True,
        "target_display": "Administrators",
        "current_as_compliance": True,
        "editable": False,
    },
    {
        "cis_id": "2.2.7",
        "name": "Back up files and directories",
        "key": "SeBackupPrivilege",
        "required": "*S-1-5-32-544",
        "default": "*S-1-5-32-544,*S-1-5-32-551",
        "is_string": True,
        "target_display": "Administrators",
        "current_as_compliance": True,
        "editable": False,
    },
]

REGISTRY_KEYS = [
    {
        "cis_id": "1.1.6",
        "name": "Relax minimum password length limits",
        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\SAM",
        "value_name": "RelaxMinimumPasswordLengthLimits",
        "value_type": "REG_DWORD",
        "required": 1,
        "default": 0,
        "missing_value": 0,
        "operator": "eq",
        "display": {0: "Disabled", 1: "Enabled"},
        "input_min": 0,
        "input_max": 1,
    },
]

SYSTEM_SERVICES = [
    {
        "cis_id": "5.1",
        "name": "Bluetooth Audio Gateway Service (BTAGService)",
        "service_name": "BTAGService",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.2",
        "name": "Bluetooth Support Service (bthserv)",
        "service_name": "bthserv",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.3",
        "name": "Computer Browser (Browser)",
        "service_name": "Browser",
        "required": 4,
        "default": 4,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.4",
        "name": "Downloaded Maps Manager (MapsBroker)",
        "service_name": "MapsBroker",
        "required": 4,
        "default": 2,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.5",
        "name": "GameInput Service (GameInputSvc)",
        "service_name": "GameInputSvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.6",
        "name": "Geolocation Service (lfsvc)",
        "service_name": "lfsvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.7",
        "name": "IIS Admin Service (IISADMIN)",
        "service_name": "IISADMIN",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.8",
        "name": "Infrared monitor service (irmon)",
        "service_name": "irmon",
        "required": 4,
        "default": 4,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.9",
        "name": "Link-Layer Topology Discovery Mapper (lltdsvc)",
        "service_name": "lltdsvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.10",
        "name": "Microsoft FTP Service (FTPSVC)",
        "service_name": "FTPSVC",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.11",
        "name": "Microsoft iSCSI Initiator Service (MSiSCSI)",
        "service_name": "MSiSCSI",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.12",
        "name": "OpenSSH SSH Server (sshd)",
        "service_name": "sshd",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.13",
        "name": "Peer Name Resolution Protocol (PNRPsvc)",
        "service_name": "PNRPsvc",
        "required": 4,
        "default": 4,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.14",
        "name": "Peer Networking Grouping (p2psvc)",
        "service_name": "p2psvc",
        "required": 4,
        "default": 4,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.15",
        "name": "Peer Networking Identity Manager (p2pimsvc)",
        "service_name": "p2pimsvc",
        "required": 4,
        "default": 4,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.16",
        "name": "PNRP Machine Name Publication Service (PNRPAutoReg)",
        "service_name": "PNRPAutoReg",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.17",
        "name": "Print Spooler (Spooler)",
        "service_name": "Spooler",
        "required": 4,
        "default": 2,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.18",
        "name": "Problem Reports and Solutions Control Panel Support (wercplsupport)",
        "service_name": "wercplsupport",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.19",
        "name": "Remote Access Auto Connection Manager (RasAuto)",
        "service_name": "RasAuto",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.20",
        "name": "Remote Desktop Configuration (SessionEnv)",
        "service_name": "SessionEnv",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.21",
        "name": "Remote Desktop Services (TermService)",
        "service_name": "TermService",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.22",
        "name": "Remote Desktop Services UserMode Port Redirector (UmRdpService)",
        "service_name": "UmRdpService",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.23",
        "name": "Remote Procedure Call (RPC) Locator (RpcLocator)",
        "service_name": "RpcLocator",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.24",
        "name": "Remote Registry (RemoteRegistry)",
        "service_name": "RemoteRegistry",
        "required": 4,
        "default": 4,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.25",
        "name": "Routing and Remote Access (RemoteAccess)",
        "service_name": "RemoteAccess",
        "required": 4,
        "default": 4,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.26",
        "name": "Server (LanmanServer)",
        "service_name": "LanmanServer",
        "required": 4,
        "default": 2,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.27",
        "name": "Simple TCP/IP Services (simptcp)",
        "service_name": "simptcp",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.28",
        "name": "SNMP Service (SNMP)",
        "service_name": "SNMP",
        "required": 4,
        "default": 2,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.29",
        "name": "Special Administration Console Helper (sacsvr)",
        "service_name": "sacsvr",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.30",
        "name": "SSDP Discovery (SSDPSRV)",
        "service_name": "SSDPSRV",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.31",
        "name": "UPnP Device Host (upnphost)",
        "service_name": "upnphost",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.32",
        "name": "Web Management Service (WMSvc)",
        "service_name": "WMSvc",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.33",
        "name": "Windows Error Reporting Service (WerSvc)",
        "service_name": "WerSvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.34",
        "name": "Windows Event Collector (Wecsvc)",
        "service_name": "Wecsvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.35",
        "name": "Windows Media Player Network Sharing Service (WMPNetworkSvc)",
        "service_name": "WMPNetworkSvc",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.36",
        "name": "Windows Mobile Hotspot Service (icssvc)",
        "service_name": "icssvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.37",
        "name": "Windows Push Notifications System Service (WpnService)",
        "service_name": "WpnService",
        "required": 4,
        "default": 2,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.38",
        "name": "Windows PushToInstall Service (PushToInstall)",
        "service_name": "PushToInstall",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.39",
        "name": "Windows Remote Management (WS-Management) (WinRM)",
        "service_name": "WinRM",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.40",
        "name": "World Wide Web Publishing Service (W3SVC)",
        "service_name": "W3SVC",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.41",
        "name": "Xbox Accessory Management Service (XboxGipSvc)",
        "service_name": "XboxGipSvc",
        "required": 4,
        "default": 3,
        "allow_missing": True,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.42",
        "name": "Xbox Live Auth Manager (XblAuthManager)",
        "service_name": "XblAuthManager",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.43",
        "name": "Xbox Live Game Save (XblGameSave)",
        "service_name": "XblGameSave",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
    {
        "cis_id": "5.44",
        "name": "Xbox Live Networking Service (XboxNetApiSvc)",
        "service_name": "XboxNetApiSvc",
        "required": 4,
        "default": 3,
        "display": {2: "Automatic", 3: "Manual", 4: "Disabled"},
    },
]

POLICY_GROUPS = {
    "net_accounts": NET_ACCOUNTS,
    "secedit": SECEDIT_POLICIES,
    "registry": REGISTRY_KEYS,
    "services": SYSTEM_SERVICES,
}

ALL_POLICIES = [
    policy
    for policies in POLICY_GROUPS.values()
    for policy in policies
]

# The application's reset baseline. Apply operations use the CIS "required"
# values, while Reset Configuration restores these original/default values.
DEFAULT_POLICY_VALUES = {
    policy["cis_id"]: policy["default"]
    for policy in ALL_POLICIES
}

POLICY_CATEGORIES = {
    "password": sorted(
        (policy for policy in ALL_POLICIES if policy["cis_id"].startswith("1.1.")),
        key=lambda policy: tuple(int(part) for part in policy["cis_id"].split(".")),
    ),
    "lockout": sorted(
        (policy for policy in ALL_POLICIES if policy["cis_id"].startswith("1.2.")),
        key=lambda policy: tuple(int(part) for part in policy["cis_id"].split(".")),
    ),
    "services": sorted(
        (policy for policy in ALL_POLICIES if policy["cis_id"].startswith("5.")),
        key=lambda policy: tuple(int(part) for part in policy["cis_id"].split(".")),
    ),
    "local_policy": sorted(
        (policy for policy in ALL_POLICIES if policy["cis_id"].startswith("2.2.")),
        key=lambda policy: tuple(int(part) for part in policy["cis_id"].split(".")),
    ),
}
